name: Java CI with Maven

# Se déclenche lors d'un push sur la branche master 
on:
  push:
    branches: [ "master" ]

# Jobs à effectuer lors de l'exécution
jobs:
  analyse-code:

    # O.S. sur lequel vont être exécutés les jobs
    runs-on: ubuntu-latest

    # Etapes à effectuer
    steps:
      # Récupération du code sur le dépot
      - uses: actions/checkout@v3

      # Configuration de JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Construction avec Maven
      - name: Build with Maven
        run: mvn -B package

      # Génération du rapport JUnit
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v4.0.3
        with:
          report_paths: 'target/surefire-reports/TEST-*.xml'