name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    # Configuration de JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
       
    # Démarrage de Docker
    #- name: Start Docker
    #  run: docker-compose -f "docker-compose.yml" up -d --build
     
    # Construction avec Maven
    - name: Build with Maven
      run: mvn -B package

    # Génération du rapport JUnit
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v4.0.3
      with:
        report_paths: 'target/surefire-reports/TEST-*.xml'

    # Ajout du rapport de la couverture du code
    - name: Add Coverage Job Summary
      run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

    # Téléchargement de l'artefact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: "Strovo API"
        path: target/*.jar
     
    # Arrêt de Docker
    #- name: Stop Docker
    #  if: always()
    #  run: docker-compose down
