name: Java CI with Maven

# Se déclenche lors d'un push sur la branche master 
on:
  push:
    branches: [ "master" ]

# Jobs à effectuer lors de l'exécution
jobs:
  build-publication-image:

    # O.S. sur lequel vont être exécutés les jobs
    runs-on: ubuntu-latest
    # Construit pour une architecture arm64
    options: --platform linux/arm64

    # Etapes à effectuer
    steps:
      # Récupération du code sur le dépot
      - uses: actions/checkout@v3
    
      # Configuration de JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      # Construction avec maven
      - name: Build with Maven
        run: mvn -B package

      # Enregistre l'artefact construit
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: "StrovoApi"
          path: target/*.jar

      # Construit et publie l'image docker de cet artefact
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: romaint1/strovo-api
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        

    